In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import json

# Import API key
#from config import yelp_key

# Incorporated citipy to determine city based on latitude and longitude
#from citipy import citipy

# Output File (CSV)
#output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

ModuleNotFoundError: No module named 'requests'

In [ ]:
# Create aiport dataframe
city_df = pd.read_csv('./output_data/City-Airport_Output.csv')
city_df.dropna(inplace = True) 
city_df.head()

In [ ]:
city_df['City']

In [ ]:
locations = city_df['City'].values.tolist()

In [ ]:
locations

In [ ]:

# TODO(uwana): Use your key here. Get it from yelp.com/developers
api_key='ULNS7I9bmX-QChjlJT0jh3dvq32P7y8c-dXnMckWKbS6oCcXUBiD4wWukKxBnwS-oVySc4BWnm6PrIbbJuOvhFhvULN8U6pImGyq9Sfl-sDeBoGcuYaZ_WfBzJZBYHYx'
headers = {'Authorization': 'Bearer %s' % api_key}


# Using the business search API.
url='https://api.yelp.com/v3/businesses/search'


locations 

# Attraction Data
# This stores the data in a map that will be populated
# location_to_attractions = {
#  'New York City': [
#    Attraction 1 Data,
#    Attraction 2 Data,
#    ...
#  ],
#  'Los Angeles': [
#    Attraction 1 Data,
#    Attraction 2 Data,
#    ...
#  ],
# }
location_to_attractions = {}

# Making a get request to the API for each location
for location in locations:
  # Use query paramaters that conform to the API: https://www.yelp.com/developers/documentation/v3/business_search
  params = {'term': 'attractions', 'location': location, 'limit': 5, 'sort_by': 'rating'}
  req = requests.get(url, params=params, headers=headers)
  location_to_attractions[location] = json.loads(req.text)

print('locations to attractions')
for location in location_to_attractions.keys():
  print('############# %s #########'.format(location.upper()))
  print(json.dumps(location_to_attractions[location], indent=4, sort_keys=True))
  print('==========================================')

print(location_to_attractions)

In [3]:
type(location_to_attractions)

NameError: name 'location_to_attractions' is not defined

In [4]:
df1 = pd.DataFrame(location_to_attractions)

NameError: name 'location_to_attractions' is not defined

In [9]:
df1

,New York City,Los Angeles,Chicago,Houston,Philadelphia,Phoenix,San Antonio,San Diego,Dallas,San Jose,...,Hialeah,Garland,Scottsdale,Irving,Chesapeake,North Las Vegas,Fremont,Baton Rouge,Richmond,San Bernardino
businesses,"[{'id': 'xOw4aafJRji9XomGunlvcQ', 'alias': 'ce...","[{'id': 'b6RlO51jkzRN3hrMsG3B3A', 'alias': 'ur...","[{'id': 'JfNZVzh052lwZKpIMgsA1g', 'alias': 'ga...","[{'id': 'rgQuVCBPP4CAs7jVaqMEXA', 'alias': 'he...","[{'id': 'ZF0tt7hn6WK3-aNWgtLcFA', 'alias': 'ea...","[{'id': '4vebxZrdYli926DzRjb6vA', 'alias': 'we...","[{'id': '_F7aLukkY_T9q1A2LgUIoQ', 'alias': 'mo...","[{'id': '9M_FW_-Ipx93I36w-_ykBg', 'alias': 'ba...","[{'id': 'bl1nSWUL9DrCxca-Y1N31g', 'alias': 'ka...","[{'id': 'dBqGe2rR6JfvrluMRcOcfg', 'alias': 'mo...",...,"[{'id': 'JKqPGItF2La1XH8LxGc1tw', 'alias': 'wy...","[{'id': 'a9fJvilz_ZwfxuFu7-gf6Q', 'alias': 'wh...","[{'id': '_NbvuglnRM0ifUHFDvIlbw', 'alias': 'pe...","[{'id': 'aOmtSdC1UUpHeOer8MOGtg', 'alias': 'vi...","[{'id': 'mfSp8Uq2N56iUEmsyqtdaQ', 'alias': 'ch...","[{'id': 'iBPyahdJRP5y0t25fF2W9w', 'alias': 'li...","[{'id': 'X9f6UkYr8-yeymgoOyVGww', 'alias': 'wi...","[{'id': 'lE4jHVvESL9h_nLtVrLxsw', 'alias': 'mi...","[{'id': 'Rm1TFt36IlejbZ459zmlzA', 'alias': 'ma...","[{'id': 'QhH5FYGK645Ppwb9alTlXQ', 'alias': 'pa..."
total,2400,3400,1300,565,724,720,397,1400,631,1100,...,656,323,778,441,257,654,562,50,186,173
region,"{'center': {'longitude': -73.99429321289062, '...","{'center': {'longitude': -118.32138061523438, ...","{'center': {'longitude': -87.67776489257812, '...","{'center': {'longitude': -95.35995483398438, '...","{'center': {'longitude': -75.17120361328125, '...","{'center': {'longitude': -112.07015991210938, ...","{'center': {'longitude': -98.514404296875, 'la...","{'center': {'longitude': -117.15408325195312, ...","{'center': {'longitude': -96.800537109375, 'la...","{'center': {'longitude': -121.88507080078125, ...",...,"{'center': {'longitude': -80.31005859375, 'lat...","{'center': {'longitude': -96.63848876953125, '...","{'center': {'longitude': -111.873779296875, 'l...","{'center': {'longitude': -96.96601867675781, '...","{'center': {'longitude': -76.29180908203125, '...","{'center': {'longitude': -115.12367248535156, ...","{'center': {'longitude': -121.9866943359375, '...","{'center': {'longitude': -91.09451293945312, '...","{'center': {'longitude': -77.49618530273438, '...","{'center': {'longitude': -117.28179931640625, ..."

In [10]:
df1.transpose()

,businesses,total,region
New York City,"[{'id': 'xOw4aafJRji9XomGunlvcQ', 'alias': 'ce...",2400,"{'center': {'longitude': -73.99429321289062, '..."
Los Angeles,"[{'id': 'b6RlO51jkzRN3hrMsG3B3A', 'alias': 'ur...",3400,"{'center': {'longitude': -118.32138061523438, ..."
Chicago,"[{'id': 'JfNZVzh052lwZKpIMgsA1g', 'alias': 'ga...",1300,"{'center': {'longitude': -87.67776489257812, '..."
Houston,"[{'id': 'rgQuVCBPP4CAs7jVaqMEXA', 'alias': 'he...",565,"{'center': {'longitude': -95.35995483398438, '..."
Philadelphia,"[{'id': 'ZF0tt7hn6WK3-aNWgtLcFA', 'alias': 'ea...",724,"{'center': {'longitude': -75.17120361328125, '..."
...,...,...,...
North Las Vegas,"[{'id': 'iBPyahdJRP5y0t25fF2W9w', 'alias': 'li...",654,"{'center': {'longitude': -115.12367248535156, ..."
Fremont,"[{'id': 'X9f6UkYr8-yeymgoOyVGww', 'alias': 'wi...",562,"{'center': {'longitude': -121.9866943359375, '..."
Baton Rouge,"[{'id': 'lE4jHVvESL9h_nLtVrLxsw', 'alias': 'mi...",50,"{'center': {'longitude': -91.09451293945312, '..."
Richmond,"[{'id': 'Rm1TFt36IlejbZ459zmlzA', 'alias': 'ma...",186,"{'center': {'longitude': -77.49618530273438, '..."
San Bernardino,"[{'id': 'QhH5FYGK645Ppwb9alTlXQ', 'alias': 'pa...",173,"{'center': {'longitude': -117.28179931640625, ..."

In [14]:
import numpy as np
# import pandas as pd
import requests
import json

# TODO(uwana): Use your key here. Get it from yelp.com/developers
api_key='ULNS7I9bmX-QChjlJT0jh3dvq32P7y8c-dXnMckWKbS6oCcXUBiD4wWukKxBnwS-oVySc4BWnm6PrIbbJuOvhFhvULN8U6pImGyq9Sfl-sDeBoGcuYaZ_WfBzJZBYHYx'
headers = {'Authorization': 'Bearer %s' % api_key}

# Using the business search API.
url='https://api.yelp.com/v3/businesses/search'


locations 

# https://www.yelp.com/developers/documentation/v3/business_search
# All the attractions data
attractions = []

# Making a get request to the API for each location
for location in locations:
  # Use query paramaters that conform to the API: https://www.yelp.com/developers/documentation/v3/business_search
  params = {'term': 'attractions', 'location': location, 'limit': 1, 'sort_by': 'rating'}
  req = requests.get(url, params=params, headers=headers)
  data = json.loads(req.text)
  businesses = data['businesses']
  for business in businesses:
    business_info = {'location': location, 'name': business['name'], 'rating': business['rating'], 
                    'review_count': business['review_count']}
    attractions.append(business_info)

attractions_json = json.dumps(attractions)
print(attractions_json)

[{"location": "New York City", "name": "Brooklyn Bridge", "rating": 4.5, "review_count": 1398}, {"location": "Los Angeles", "name": "Urban Light at LACMA", "rating": 4.5, "review_count": 522}, {"location": "Chicago", "name": "Garfield Park Conservatory", "rating": 5.0, "review_count": 632}, {"location": "Houston", "name": "Hermann Park Conservancy", "rating": 4.5, "review_count": 209}, {"location": "Philadelphia", "name": "Eastern State Penitentiary Historic Site", "rating": 4.5, "review_count": 792}, {"location": "Phoenix", "name": "Western Destinations", "rating": 5.0, "review_count": 50}, {"location": "San Antonio", "name": "Morgan's Wonderland", "rating": 5.0, "review_count": 96}, {"location": "San Diego", "name": "Balboa Park", "rating": 5.0, "review_count": 2124}, {"location": "Dallas", "name": "Katy Trail", "rating": 4.5, "review_count": 215}, {"location": "San Jose", "name": "Mount Hermon Adventures", "rating": 5.0, "review_count": 524}, {"location": "Austin", "name": "Lake Travis Zipline Adventures", "rating": 5.0, "review_count": 590}, {"location": "Jacksonville", "name": "Catty Shack Ranch Wildlife Sanctuary", "rating": 5.0, "review_count": 122}, {"location": "San Francisco", "name": "Tom and Jerry's House", "rating": 5.0, "review_count": 87}, {"location": "Indianapolis", "name": "White River State Park", "rating": 5.0, "review_count": 75}, {"location": "Columbus", "name": "Columbus Zoo and Aquarium", "rating": 4.5, "review_count": 450}, {"location": "Fort Worth", "name": "Fort Worth Water Gardens", "rating": 4.5, "review_count": 221}, {"location": "Charlotte", "name": "Funny Bus", "rating": 4.5, "review_count": 152}, {"location": "Seattle", "name": "Chihuly Garden and Glass", "rating": 4.5, "review_count": 2398}, {"location": "Denver", "name": "Chautauqua Park", "rating": 5.0, "review_count": 264}, {"location": "El Paso", "name": "Plaza Theatre", "rating": 4.5, "review_count": 33}, {"location": "Detroit", "name": "Detroit Institute of Arts", "rating": 4.5, "review_count": 422}, {"location": "Washington", "name": "Leavenworth Reindeer Farm", "rating": 5.0, "review_count": 64}, {"location": "Boston", "name": "Freedom Trail Foundation", "rating": 4.5, "review_count": 769}, {"location": "Memphis", "name": "National Civil Rights Museum", "rating": 4.5, "review_count": 648}, {"location": "Nashville", "name": "NashTrash Tours", "rating": 4.5, "review_count": 155}, {"location": "Portland", "name": "Forest Park", "rating": 5.0, "review_count": 221}, {"location": "Oklahoma City", "name": "Oklahoma City National Memorial & Museum", "rating": 5.0, "review_count": 345}, {"location": "Las Vegas", "name": "Sin City Smash", "rating": 5.0, "review_count": 115}, {"location": "Baltimore", "name": "The Walters Art Museum", "rating": 4.5, "review_count": 206}, {"location": "Louisville", "name": "Angel's Envy", "rating": 4.5, "review_count": 472}, {"location": "Milwaukee", "name": "Milwaukee Art Museum", "rating": 4.5, "review_count": 344}, {"location": "Albuquerque", "name": "Rainbow Ryders", "rating": 4.5, "review_count": 155}, {"location": "Tucson", "name": "Arizona-Sonora Desert Museum", "rating": 4.5, "review_count": 414}, {"location": "Fresno", "name": "Fresno Chaffee Zoo", "rating": 4.5, "review_count": 421}, {"location": "Sacramento", "name": "California State Railroad Museum", "rating": 4.5, "review_count": 532}, {"location": "Kansas City", "name": "The Nelson-Atkins Museum of Art", "rating": 5.0, "review_count": 459}, {"location": "Long Beach", "name": "Gondola Getaway", "rating": 4.5, "review_count": 501}, {"location": "Mesa", "name": "Riparian Preserve at Water Ranch", "rating": 4.5, "review_count": 172}, {"location": "Atlanta", "name": "Unexpected Atlanta Walking Tours", "rating": 5.0, "review_count": 86}, {"location": "Virginia Beach", "name": "The Adventure Park At Virginia Aquarium", "rating": 4.5, "review_count": 127}, {"location": "Raleigh", "name": "Sarah P Duke Gardens", "rating": 5.0, "review_count": 254}, {"location": "Omaha", "name": "Omaha's Henry Doorly Zoo and Aquarium", "rating": 4.5, "review_count": 540}, {"location": "Miami", "name": "Everglades Nature Tours", "rating": 5.0, "review_count": 124}, {"location": "Oakland", "name": "Redwood Valley Railway", "rating": 5.0, "review_count": 179}, {"location": "Minneapolis", "name": "Lake Harriet", "rating": 5.0, "review_count": 83}, {"location": "Tulsa", "name": "Gathering Place", "rating": 4.5, "review_count": 169}, {"location": "Wichita", "name": "Keeper Of The Plains Plaza", "rating": 5.0, "review_count": 26}, {"location": "New Orleans", "name": "New Orleans Kayak Swamp Tours", "rating": 5.0, "review_count": 197}, {"location": "Arlington", "name": "Cedar Ridge Preserve", "rating": 4.5, "review_count": 203}, {"location": "Cleveland", "name": "The Cleveland Museum of Art", "rating": 5.0, "review_count": 437}, {"location": "Bakersfield", "name": "Bakersfield River Run", "rating": 4.5, "review_count": 74}, {"location": "Tampa", "name": "The Tampa Riverwalk", "rating": 4.5, "review_count": 189}, {"location": "Aurora", "name": "Dreamtime Creations", "rating": 3.0, "review_count": 9}, {"location": "Honolulu", "name": "WWII Red Light District Tour", "rating": 5.0, "review_count": 68}, {"location": "Anaheim", "name": "Lights on Miracle Hill", "rating": 5.0, "review_count": 50}, {"location": "Santa Ana", "name": "Susan Grau", "rating": 5.0, "review_count": 247}, {"location": "Corpus Christi", "name": "USS Lexington Museum", "rating": 4.5, "review_count": 247}, {"location": "Riverside", "name": "National Museum of the United States Air Force", "rating": 5.0, "review_count": 325}, {"location": "St. Louis", "name": "Forest Park", "rating": 5.0, "review_count": 292}, {"location": "Lexington", "name": "Keeneland", "rating": 4.5, "review_count": 139}, {"location": "Pittsburgh", "name": "Bicycle Heaven", "rating": 5.0, "review_count": 189}, {"location": "Saint Paul", "name": "Arkadia Retrocade", "rating": 5.0, "review_count": 46}, {"location": "Anchorage", "name": "Anchorage Museum", "rating": 4.5, "review_count": 179}, {"location": "Cincinnati", "name": "Smale Riverfront Park", "rating": 5.0, "review_count": 105}, {"location": "Henderson", "name": "Sin City Smash", "rating": 5.0, "review_count": 115}, {"location": "Greensboro", "name": "Greensboro Science Center", "rating": 4.5, "review_count": 127}, {"location": "Plano", "name": "Vitruvian Park", "rating": 4.5, "review_count": 72}, {"location": "Newark", "name": "Scott's Pizza Tours", "rating": 5.0, "review_count": 319}, {"location": "Toledo", "name": "Toledo Museum of Art", "rating": 4.5, "review_count": 117}, {"location": "Lincoln", "name": "Comfort Inn & Suites", "rating": 3.0, "review_count": 5}, {"location": "Orlando", "name": "Diagon Alley", "rating": 4.5, "review_count": 241}, {"location": "Chula Vista", "name": "Balboa Park", "rating": 5.0, "review_count": 2124}, {"location": "Jersey City", "name": "The High Line", "rating": 4.5, "review_count": 2354}, {"location": "Chandler", "name": "Western Destinations", "rating": 5.0, "review_count": 50}, {"location": "Fort Wayne", "name": "Auburn Cord Duesenberg Automobile Museum", "rating": 5.0, "review_count": 36}, {"location": "Buffalo", "name": "Cave Of The Winds", "rating": 4.5, "review_count": 197}, {"location": "Durham", "name": "Sarah P Duke Gardens", "rating": 5.0, "review_count": 254}, {"location": "St. Petersburg", "name": "Gators Parasail", "rating": 5.0, "review_count": 63}, {"location": "Irvine", "name": "Susan Grau", "rating": 5.0, "review_count": 247}, {"location": "Laredo", "name": "La Posada Hotel", "rating": 3.5, "review_count": 43}, {"location": "Lubbock", "name": "Hilton Garden Inn Lubbock", "rating": 4.5, "review_count": 37}, {"location": "Madison", "name": "Wisconsin State Capitol", "rating": 4.5, "review_count": 101}, {"location": "Gilbert", "name": "Veterans Oasis Park", "rating": 5.0, "review_count": 102}, {"location": "Norfolk", "name": "Chrysler Museum of Art", "rating": 5.0, "review_count": 158}, {"location": "Reno", "name": "Tahoe Vista Treetop Adventure Park", "rating": 5.0, "review_count": 150}, {"location": "Winston-Salem", "name": "Fiddlin' Fish Brewing", "rating": 4.5, "review_count": 79}, {"location": "Glendale", "name": "Arlington Garden in Pasadena", "rating": 4.5, "review_count": 249}, {"location": "Hialeah", "name": "Wynwood Walls", "rating": 4.5, "review_count": 1027}, {"location": "Garland", "name": "Dallas Arboretum", "rating": 4.5, "review_count": 822}, {"location": "Scottsdale", "name": "Western Destinations", "rating": 5.0, "review_count": 50}, {"location": "Irving", "name": "Vitruvian Park", "rating": 4.5, "review_count": 72}, {"location": "Chesapeake", "name": "Chrysler Museum of Art", "rating": 5.0, "review_count": 158}, {"location": "North Las Vegas", "name": "Lip Smacking Foodie Tours", "rating": 5.0, "review_count": 389}, {"location": "Fremont", "name": "Widmer World", "rating": 5.0, "review_count": 52}, {"location": "Baton Rouge", "name": "Mike the Tiger Habitat", "rating": 5.0, "review_count": 37}, {"location": "Richmond", "name": "Maymont", "rating": 5.0, "review_count": 291}, {"location": "San Bernardino", "name": "Palm Springs Aerial Tramway", "rating": 4.5, "review_count": 1310}]

In [15]:
list(business)

['id',
 'alias',
 'name',
 'image_url',
 'is_closed',
 'url',
 'review_count',
 'categories',
 'rating',
 'coordinates',
 'transactions',
 'location',
 'phone',
 'display_phone',
 'distance']

In [16]:
attractions

[{'location': 'New York City',
  'name': 'Brooklyn Bridge',
  'rating': 4.5,
  'review_count': 1398},
 {'location': 'Los Angeles',
  'name': 'Urban Light at LACMA',
  'rating': 4.5,
  'review_count': 522},
 {'location': 'Chicago',
  'name': 'Garfield Park Conservatory',
  'rating': 5.0,
  'review_count': 632},
 {'location': 'Houston',
  'name': 'Hermann Park Conservancy',
  'rating': 4.5,
  'review_count': 209},
 {'location': 'Philadelphia',
  'name': 'Eastern State Penitentiary Historic Site',
  'rating': 4.5,
  'review_count': 792},
 {'location': 'Phoenix',
  'name': 'Western Destinations',
  'rating': 5.0,
  'review_count': 50},
 {'location': 'San Antonio',
  'name': "Morgan's Wonderland",
  'rating': 5.0,
  'review_count': 96},
 {'location': 'San Diego',
  'name': 'Balboa Park',
  'rating': 5.0,
  'review_count': 2124},
 {'location': 'Dallas',
  'name': 'Katy Trail',
  'rating': 4.5,
  'review_count': 215},
 {'location': 'San Jose',
  'name': 'Mount Hermon Adventures',
  'rating': 5.0,
  'review_count': 524},
 {'location': 'Austin',
  'name': 'Lake Travis Zipline Adventures',
  'rating': 5.0,
  'review_count': 590},
 {'location': 'Jacksonville',
  'name': 'Catty Shack Ranch Wildlife Sanctuary',
  'rating': 5.0,
  'review_count': 122},
 {'location': 'San Francisco',
  'name': "Tom and Jerry's House",
  'rating': 5.0,
  'review_count': 87},
 {'location': 'Indianapolis',
  'name': 'White River State Park',
  'rating': 5.0,
  'review_count': 75},
 {'location': 'Columbus',
  'name': 'Columbus Zoo and Aquarium',
  'rating': 4.5,
  'review_count': 450},
 {'location': 'Fort Worth',
  'name': 'Fort Worth Water Gardens',
  'rating': 4.5,
  'review_count': 221},
 {'location': 'Charlotte',
  'name': 'Funny Bus',
  'rating': 4.5,
  'review_count': 152},
 {'location': 'Seattle',
  'name': 'Chihuly Garden and Glass',
  'rating': 4.5,
  'review_count': 2398},
 {'location': 'Denver',
  'name': 'Chautauqua Park',
  'rating': 5.0,
  'review_count': 264},
 {'location': 'El Paso',
  'name': 'Plaza Theatre',
  'rating': 4.5,
  'review_count': 33},
 {'location': 'Detroit',
  'name': 'Detroit Institute of Arts',
  'rating': 4.5,
  'review_count': 422},
 {'location': 'Washington',
  'name': 'Leavenworth Reindeer Farm',
  'rating': 5.0,
  'review_count': 64},
 {'location': 'Boston',
  'name': 'Freedom Trail Foundation',
  'rating': 4.5,
  'review_count': 769},
 {'location': 'Memphis',
  'name': 'National Civil Rights Museum',
  'rating': 4.5,
  'review_count': 648},
 {'location': 'Nashville',
  'name': 'NashTrash Tours',
  'rating': 4.5,
  'review_count': 155},
 {'location': 'Portland',
  'name': 'Forest Park',
  'rating': 5.0,
  'review_count': 221},
 {'location': 'Oklahoma City',
  'name': 'Oklahoma City National Memorial & Museum',
  'rating': 5.0,
  'review_count': 345},
 {'location': 'Las Vegas',
  'name': 'Sin City Smash',
  'rating': 5.0,
  'review_count': 115},
 {'location': 'Baltimore',
  'name': 'The Walters Art Museum',
  'rating': 4.5,
  'review_count': 206},
 {'location': 'Louisville',
  'name': "Angel's Envy",
  'rating': 4.5,
  'review_count': 472},
 {'location': 'Milwaukee',
  'name': 'Milwaukee Art Museum',
  'rating': 4.5,
  'review_count': 344},
 {'location': 'Albuquerque',
  'name': 'Rainbow Ryders',
  'rating': 4.5,
  'review_count': 155},
 {'location': 'Tucson',
  'name': 'Arizona-Sonora Desert Museum',
  'rating': 4.5,
  'review_count': 414},
 {'location': 'Fresno',
  'name': 'Fresno Chaffee Zoo',
  'rating': 4.5,
  'review_count': 421},
 {'location': 'Sacramento',
  'name': 'California State Railroad Museum',
  'rating': 4.5,
  'review_count': 532},
 {'location': 'Kansas City',
  'name': 'The Nelson-Atkins Museum of Art',
  'rating': 5.0,
  'review_count': 459},
 {'location': 'Long Beach',
  'name': 'Gondola Getaway',
  'rating': 4.5,
  'review_count': 501},
 {'location': 'Mesa',
  'name': 'Riparian Preserve at Water Ranch',
  'rating': 4.5,
  'review_count': 172},
 {'location': 'Atlanta',
  'name': 'Unexpected Atlanta Walking Tours',
  'rating': 5.0,
  'review_count': 86},
 {'location': 'Virginia Beach',
  'name': 'The Adventure Park At Virginia Aquarium',
  'rating': 4.5,
  'review_count': 127},
 {'location': 'Raleigh',
  'name': 'Sarah P Duke Gardens',
  'rating': 5.0,
  'review_count': 254},
 {'location': 'Omaha',
  'name': "Omaha's Henry Doorly Zoo and Aquarium",
  'rating': 4.5,
  'review_count': 540},
 {'location': 'Miami',
  'name': 'Everglades Nature Tours',
  'rating': 5.0,
  'review_count': 124},
 {'location': 'Oakland',
  'name': 'Redwood Valley Railway',
  'rating': 5.0,
  'review_count': 179},
 {'location': 'Minneapolis',
  'name': 'Lake Harriet',
  'rating': 5.0,
  'review_count': 83},
 {'location': 'Tulsa',
  'name': 'Gathering Place',
  'rating': 4.5,
  'review_count': 169},
 {'location': 'Wichita',
  'name': 'Keeper Of The Plains Plaza',
  'rating': 5.0,
  'review_count': 26},
 {'location': 'New Orleans',
  'name': 'New Orleans Kayak Swamp Tours',
  'rating': 5.0,
  'review_count': 197},
 {'location': 'Arlington',
  'name': 'Cedar Ridge Preserve',
  'rating': 4.5,
  'review_count': 203},
 {'location': 'Cleveland',
  'name': 'The Cleveland Museum of Art',
  'rating': 5.0,
  'review_count': 437},
 {'location': 'Bakersfield',
  'name': 'Bakersfield River Run',
  'rating': 4.5,
  'review_count': 74},
 {'location': 'Tampa',
  'name': 'The Tampa Riverwalk',
  'rating': 4.5,
  'review_count': 189},
 {'location': 'Aurora',
  'name': 'Dreamtime Creations',
  'rating': 3.0,
  'review_count': 9},
 {'location': 'Honolulu',
  'name': 'WWII Red Light District Tour',
  'rating': 5.0,
  'review_count': 68},
 {'location': 'Anaheim',
  'name': 'Lights on Miracle Hill',
  'rating': 5.0,
  'review_count': 50},
 {'location': 'Santa Ana',
  'name': 'Susan Grau',
  'rating': 5.0,
  'review_count': 247},
 {'location': 'Corpus Christi',
  'name': 'USS Lexington Museum',
  'rating': 4.5,
  'review_count': 247},
 {'location': 'Riverside',
  'name': 'National Museum of the United States Air Force',
  'rating': 5.0,
  'review_count': 325},
 {'location': 'St. Louis',
  'name': 'Forest Park',
  'rating': 5.0,
  'review_count': 292},
 {'location': 'Lexington',
  'name': 'Keeneland',
  'rating': 4.5,
  'review_count': 139},
 {'location': 'Pittsburgh',
  'name': 'Bicycle Heaven',
  'rating': 5.0,
  'review_count': 189},
 {'location': 'Saint Paul',
  'name': 'Arkadia Retrocade',
  'rating': 5.0,
  'review_count': 46},
 {'location': 'Anchorage',
  'name': 'Anchorage Museum',
  'rating': 4.5,
  'review_count': 179},
 {'location': 'Cincinnati',
  'name': 'Smale Riverfront Park',
  'rating': 5.0,
  'review_count': 105},
 {'location': 'Henderson',
  'name': 'Sin City Smash',
  'rating': 5.0,
  'review_count': 115},
 {'location': 'Greensboro',
  'name': 'Greensboro Science Center',
  'rating': 4.5,
  'review_count': 127},
 {'location': 'Plano',
  'name': 'Vitruvian Park',
  'rating': 4.5,
  'review_count': 72},
 {'location': 'Newark',
  'name': "Scott's Pizza Tours",
  'rating': 5.0,
  'review_count': 319},
 {'location': 'Toledo',
  'name': 'Toledo Museum of Art',
  'rating': 4.5,
  'review_count': 117},
 {'location': 'Lincoln',
  'name': 'Comfort Inn & Suites',
  'rating': 3.0,
  'review_count': 5},
 {'location': 'Orlando',
  'name': 'Diagon Alley',
  'rating': 4.5,
  'review_count': 241},
 {'location': 'Chula Vista',
  'name': 'Balboa Park',
  'rating': 5.0,
  'review_count': 2124},
 {'location': 'Jersey City',
  'name': 'The High Line',
  'rating': 4.5,
  'review_count': 2354},
 {'location': 'Chandler',
  'name': 'Western Destinations',
  'rating': 5.0,
  'review_count': 50},
 {'location': 'Fort Wayne',
  'name': 'Auburn Cord Duesenberg Automobile Museum',
  'rating': 5.0,
  'review_count': 36},
 {'location': 'Buffalo',
  'name': 'Cave Of The Winds',
  'rating': 4.5,
  'review_count': 197},
 {'location': 'Durham',
  'name': 'Sarah P Duke Gardens',
  'rating': 5.0,
  'review_count': 254},
 {'location': 'St. Petersburg',
  'name': 'Gators Parasail',
  'rating': 5.0,
  'review_count': 63},
 {'location': 'Irvine',
  'name': 'Susan Grau',
  'rating': 5.0,
  'review_count': 247},
 {'location': 'Laredo',
  'name': 'La Posada Hotel',
  'rating': 3.5,
  'review_count': 43},
 {'location': 'Lubbock',
  'name': 'Hilton Garden Inn Lubbock',
  'rating': 4.5,
  'review_count': 37},
 {'location': 'Madison',
  'name': 'Wisconsin State Capitol',
  'rating': 4.5,
  'review_count': 101},
 {'location': 'Gilbert',
  'name': 'Veterans Oasis Park',
  'rating': 5.0,
  'review_count': 102},
 {'location': 'Norfolk',
  'name': 'Chrysler Museum of Art',
  'rating': 5.0,
  'review_count': 158},
 {'location': 'Reno',
  'name': 'Tahoe Vista Treetop Adventure Park',
  'rating': 5.0,
  'review_count': 150},
 {'location': 'Winston-Salem',
  'name': "Fiddlin' Fish Brewing",
  'rating': 4.5,
  'review_count': 79},
 {'location': 'Glendale',
  'name': 'Arlington Garden in Pasadena',
  'rating': 4.5,
  'review_count': 249},
 {'location': 'Hialeah',
  'name': 'Wynwood Walls',
  'rating': 4.5,
  'review_count': 1027},
 {'location': 'Garland',
  'name': 'Dallas Arboretum',
  'rating': 4.5,
  'review_count': 822},
 {'location': 'Scottsdale',
  'name': 'Western Destinations',
  'rating': 5.0,
  'review_count': 50},
 {'location': 'Irving',
  'name': 'Vitruvian Park',
  'rating': 4.5,
  'review_count': 72},
 {'location': 'Chesapeake',
  'name': 'Chrysler Museum of Art',
  'rating': 5.0,
  'review_count': 158},
 {'location': 'North Las Vegas',
  'name': 'Lip Smacking Foodie Tours',
  'rating': 5.0,
  'review_count': 389},
 {'location': 'Fremont',
  'name': 'Widmer World',
  'rating': 5.0,
  'review_count': 52},
 {'location': 'Baton Rouge',
  'name': 'Mike the Tiger Habitat',
  'rating': 5.0,
  'review_count': 37},
 {'location': 'Richmond',
  'name': 'Maymont',
  'rating': 5.0,
  'review_count': 291},
 {'location': 'San Bernardino',
  'name': 'Palm Springs Aerial Tramway',
  'rating': 4.5,
  'review_count': 1310}]

In [25]:
type(attractions)

list

In [26]:
yelp_df = pd.DataFrame(attractions)

In [27]:
yelp_df.head(100)

,location,name,rating,review_count
0,New York City,Brooklyn Bridge,4.5,1398
1,Los Angeles,Urban Light at LACMA,4.5,522
2,Chicago,Garfield Park Conservatory,5.0,632
3,Houston,Hermann Park Conservancy,4.5,209
4,Philadelphia,Eastern State Penitentiary Historic Site,4.5,792
...,...,...,...,...
92,North Las Vegas,Lip Smacking Foodie Tours,5.0,389
93,Fremont,Widmer World,5.0,52
94,Baton Rouge,Mike the Tiger Habitat,5.0,37
95,Richmond,Maymont,5.0,291
96,San Bernardino,Palm Springs Aerial Tramway,4.5,1310

In [31]:
yelp = yelp_df.to_csv()

In [32]:
yelp

",location,name,rating,review_count\n0,New York City,Brooklyn Bridge,4.5,1398\n1,Los Angeles,Urban Light at LACMA,4.5,522\n2,Chicago,Garfield Park Conservatory,5.0,632\n3,Houston,Hermann Park Conservancy,4.5,209\n4,Philadelphia,Eastern State Penitentiary Historic Site,4.5,792\n5,Phoenix,Western Destinations,5.0,50\n6,San Antonio,Morgan's Wonderland,5.0,96\n7,San Diego,Balboa Park,5.0,2124\n8,Dallas,Katy Trail,4.5,215\n9,San Jose,Mount Hermon Adventures,5.0,524\n10,Austin,Lake Travis Zipline Adventures,5.0,590\n11,Jacksonville,Catty Shack Ranch Wildlife Sanctuary,5.0,122\n12,San Francisco,Tom and Jerry's House,5.0,87\n13,Indianapolis,White River State Park,5.0,75\n14,Columbus,Columbus Zoo and Aquarium,4.5,450\n15,Fort Worth,Fort Worth Water Gardens,4.5,221\n16,Charlotte,Funny Bus,4.5,152\n17,Seattle,Chihuly Garden and Glass,4.5,2398\n18,Denver,Chautauqua Park,5.0,264\n19,El Paso,Plaza Theatre,4.5,33\n20,Detroit,Detroit Institute of Arts,4.5,422\n21,Washington,Leavenworth Reindeer Farm,5.0,64\n22,Boston,Freedom Trail Foundation,4.5,769\n23,Memphis,National Civil Rights Museum,4.5,648\n24,Nashville,NashTrash Tours,4.5,155\n25,Portland,Forest Park,5.0,221\n26,Oklahoma City,Oklahoma City National Memorial & Museum,5.0,345\n27,Las Vegas,Sin City Smash,5.0,115\n28,Baltimore,The Walters Art Museum,4.5,206\n29,Louisville,Angel's Envy,4.5,472\n30,Milwaukee,Milwaukee Art Museum,4.5,344\n31,Albuquerque,Rainbow Ryders,4.5,155\n32,Tucson,Arizona-Sonora Desert Museum,4.5,414\n33,Fresno,Fresno Chaffee Zoo,4.5,421\n34,Sacramento,California State Railroad Museum,4.5,532\n35,Kansas City,The Nelson-Atkins Museum of Art,5.0,459\n36,Long Beach,Gondola Getaway,4.5,501\n37,Mesa,Riparian Preserve at Water Ranch,4.5,172\n38,Atlanta,Unexpected Atlanta Walking Tours,5.0,86\n39,Virginia Beach,The Adventure Park At Virginia Aquarium,4.5,127\n40,Raleigh,Sarah P Duke Gardens,5.0,254\n41,Omaha,Omaha's Henry Doorly Zoo and Aquarium,4.5,540\n42,Miami,Everglades Nature Tours,5.0,124\n43,Oakland,Redwood Valley Railway,5.0,179\n44,Minneapolis,Lake Harriet,5.0,83\n45,Tulsa,Gathering Place,4.5,169\n46,Wichita,Keeper Of The Plains Plaza,5.0,26\n47,New Orleans,New Orleans Kayak Swamp Tours,5.0,197\n48,Arlington,Cedar Ridge Preserve,4.5,203\n49,Cleveland,The Cleveland Museum of Art,5.0,437\n50,Bakersfield,Bakersfield River Run,4.5,74\n51,Tampa,The Tampa Riverwalk,4.5,189\n52,Aurora,Dreamtime Creations,3.0,9\n53,Honolulu,WWII Red Light District Tour,5.0,68\n54,Anaheim,Lights on Miracle Hill,5.0,50\n55,Santa Ana,Susan Grau,5.0,247\n56,Corpus Christi,USS Lexington Museum,4.5,247\n57,Riverside,National Museum of the United States Air Force,5.0,325\n58,St. Louis,Forest Park,5.0,292\n59,Lexington,Keeneland,4.5,139\n60,Pittsburgh,Bicycle Heaven,5.0,189\n61,Saint Paul,Arkadia Retrocade,5.0,46\n62,Anchorage,Anchorage Museum,4.5,179\n63,Cincinnati,Smale Riverfront Park,5.0,105\n64,Henderson,Sin City Smash,5.0,115\n65,Greensboro,Greensboro Science Center,4.5,127\n66,Plano,Vitruvian Park,4.5,72\n67,Newark,Scott's Pizza Tours,5.0,319\n68,Toledo,Toledo Museum of Art,4.5,117\n69,Lincoln,Comfort Inn & Suites,3.0,5\n70,Orlando,Diagon Alley,4.5,241\n71,Chula Vista,Balboa Park,5.0,2124\n72,Jersey City,The High Line,4.5,2354\n73,Chandler,Western Destinations,5.0,50\n74,Fort Wayne,Auburn Cord Duesenberg Automobile Museum,5.0,36\n75,Buffalo,Cave Of The Winds,4.5,197\n76,Durham,Sarah P Duke Gardens,5.0,254\n77,St. Petersburg,Gators Parasail,5.0,63\n78,Irvine,Susan Grau,5.0,247\n79,Laredo,La Posada Hotel,3.5,43\n80,Lubbock,Hilton Garden Inn Lubbock,4.5,37\n81,Madison,Wisconsin State Capitol,4.5,101\n82,Gilbert,Veterans Oasis Park,5.0,102\n83,Norfolk,Chrysler Museum of Art,5.0,158\n84,Reno,Tahoe Vista Treetop Adventure Park,5.0,150\n85,Winston-Salem,Fiddlin' Fish Brewing,4.5,79\n86,Glendale,Arlington Garden in Pasadena,4.5,249\n87,Hialeah,Wynwood Walls,4.5,1027\n88,Garland,Dallas Arboretum,4.5,822\n89,Scottsdale,Western Destinations,5.0,50\n90,Irving,Vitruvian Park,4.5,72\n91,Chesapeake,Chrysler Museum of Art,5.0,158\n92,North Las Vegas,Lip Smacking Foodie Tours,5.0,389\n93,Fremont,Widmer World,5.0,52\n94,Baton Rouge,Mike the Tiger Habitat,5.0,37\n95,Richmond,Maymont,5.0,291\n96,San Bernardino,Palm Springs Aerial Tramway,4.5,1310\n"

In [35]:
yelp_df.to_csv("yelp.csv", encoding="utf-8", index=False)