In [1]:
# Dependencies
import pandas as pd
import numpy as np
import json
import requests
from datetime import datetime
from config import api_key

In [2]:
cities_pd = pd.read_csv("./Resources/Airport_Output.csv")
cities_pd=cities_pd.head()
print(cities_pd)

   Unnamed: 0           City         State        Lat         Lng  \
0           0  New York City      New York  40.712775  -74.005973
1           1    Los Angeles    California  34.052234 -118.243685
2           2        Chicago      Illinois  41.878114  -87.629798
3           3        Houston         Texas  29.760427  -95.369803
4           4   Philadelphia  Pennsylvania  39.952584  -75.165222

                           Airport Name                   Airport Address  \
0  Newark Liberty International Airport             3 Brewster Rd, Newark
1     Los Angeles International Airport          1 World Way, Los Angeles
2          O'Hare International Airport       10000 W O'Hare Ave, Chicago
3              William P. Hobby Airport        7800 Airport Blvd, Houston
4    Philadelphia International Airport  8000 Essington Ave, Philadelphia

   Airport Rating Airport Code
0             3.2          EWR
1             3.5          LAX
2             3.6          ORD
3             4.0          HOU
4             3.3          PHL

In [14]:
city_name=[]
lat=[]
lng=[]
dateTime=[]
date=[]
time=[]
sunrise=[]
sunset=[]
pressure=[]
humidity=[]
wind_speed=[]
low_temp=[]
high_temp=[]
descriptor=[]

In [15]:
for index, row in cities_pd.iterrows():
    cur_lat = row['Lat']
    cur_lng = row['Lng']
    # Save config information
    url="https://api.openweathermap.org/data/2.5/onecall?units=imperial&lat=" + str(cur_lat) + "&lon=" + str(cur_lng) + "&"
    # Build query URL
    query_url = url + "appid=" + api_key
    #print(query_url)
    # Get weather data
    weather_response = requests.get(query_url)
    weather_json = weather_response.json()
    num_days=len(weather_json['daily'])
    for x in range(num_days):
        # Get the temperature from each day of the response
        #print(x)
        city_name.append(row['City'])
        lat.append(cur_lat)
        lng.append(cur_lng)
        dt_object=datetime.fromtimestamp(weather_json['daily'][x]['dt'])
        timestampStr = dt_object.strftime("%d-%b-%Y (%H:%M:%S.%f)")
        time_list=timestampStr.split()
        dateTime.append(time_list[0])
        dt_object=datetime.fromtimestamp(weather_json['daily'][x]['sunrise'])
        timestampStr = dt_object.strftime("%d-%b-%Y (%H:%M:%S.%f)")
        time_list=timestampStr.split()
        sunrise.append(time_list[1])
        dt_object=datetime.fromtimestamp(weather_json['daily'][x]['sunset'])
        timestampStr = dt_object.strftime("%d-%b-%Y (%H:%M:%S.%f)")
        time_list=timestampStr.split()
        sunset.append(time_list[1])
        pressure.append(weather_json['daily'][x]['pressure'])
        humidity.append(weather_json['daily'][x]['humidity'])
        wind_speed.append(weather_json['daily'][x]['wind_speed'])
        low_temp.append(weather_json['daily'][x]['temp']['min'])
        high_temp.append(weather_json['daily'][x]['temp']['max'])
        descriptor.append(weather_json['daily'][x]['weather'][0]['main'])

In [16]:
weather_dict = {
    "city": city_name,
    "lat": lat,
    "lng": lng,
    "dateTime": dateTime,
    "sunrise": sunrise,
    "sunset": sunset,
    "pressure": pressure,
    "humidity": humidity,
    "wind_speed (MPH)": wind_speed,
    "low_temp (degF)": low_temp,
    "high_temp (degF)": high_temp,
    "descriptor": descriptor,
}
weather_data = pd.DataFrame(weather_dict)
weather_data.head(20)

,city,lat,lng,dateTime,sunrise,sunset,pressure,humidity,wind_speed (MPH),low_temp (degF),high_temp (degF),descriptor
0,New York City,40.712775,-74.005973,11-Mar-2021,(06:13:55.000000),(17:58:13.000000),1024,46,9.31,43.79,64.15,Clouds
1,New York City,40.712775,-74.005973,12-Mar-2021,(06:12:16.000000),(17:59:17.000000),1021,34,8.55,46.45,60.03,Rain
2,New York City,40.712775,-74.005973,13-Mar-2021,(06:10:38.000000),(18:00:22.000000),1028,22,8.08,32.49,48.34,Clear
3,New York City,40.712775,-74.005973,14-Mar-2021,(07:08:59.000000),(19:01:26.000000),1016,36,17.85,34.50,52.54,Clear
4,New York City,40.712775,-74.005973,15-Mar-2021,(07:07:20.000000),(19:02:30.000000),1029,12,5.59,26.19,41.88,Clear
5,New York City,40.712775,-74.005973,16-Mar-2021,(07:05:40.000000),(19:03:34.000000),1018,92,18.92,35.83,42.73,Rain
6,New York City,40.712775,-74.005973,17-Mar-2021,(07:04:00.000000),(19:04:37.000000),1010,55,14.67,41.70,50.99,Clouds
7,New York City,40.712775,-74.005973,18-Mar-2021,(07:02:20.000000),(19:05:41.000000),1018,48,0.58,38.88,49.96,Rain
8,Los Angeles,34.052234,-118.243685,11-Mar-2021,(09:08:26.000000),(20:57:31.000000),1018,44,7.38,48.65,56.80,Rain
9,Los Angeles,34.052234,-118.243685,12-Mar-2021,(09:07:06.000000),(20:58:18.000000),1020,38,7.96,49.14,59.05,Clouds
10,Los Angeles,34.052234,-118.243685,13-Mar-2021,(09:05:45.000000),(20:59:05.000000),1023,39,4.50,50.72,65.10,Clear
11,Los Angeles,34.052234,-118.243685,14-Mar-2021,(10:04:23.000000),(21:59:51.000000),1020,45,8.75,52.77,64.72,Clear
12,Los Angeles,34.052234,-118.243685,15-Mar-2021,(10:03:01.000000),(22:00:38.000000),1015,62,8.52,52.83,60.28,Clouds
13,Los Angeles,34.052234,-118.243685,16-Mar-2021,(10:01:39.000000),(22:01:24.000000),1015,27,6.62,49.64,62.01,Clear
14,Los Angeles,34.052234,-118.243685,17-Mar-2021,(10:00:17.000000),(22:02:10.000000),1017,20,7.72,53.02,67.98,Clouds
15,Los Angeles,34.052234,-118.243685,18-Mar-2021,(09:58:55.000000),(22:02:56.000000),1017,21,7.76,58.60,72.59,Clear
16,Chicago,41.878114,-87.629798,11-Mar-2021,(07:08:45.000000),(18:52:18.000000),1018,50,14.20,44.11,58.15,Rain
17,Chicago,41.878114,-87.629798,12-Mar-2021,(07:07:04.000000),(18:53:26.000000),1032,43,3.62,38.14,47.08,Clouds
18,Chicago,41.878114,-87.629798,13-Mar-2021,(07:05:22.000000),(18:54:34.000000),1032,40,3.87,36.16,48.18,Clouds
19,Chicago,41.878114,-87.629798,14-Mar-2021,(08:03:39.000000),(19:55:41.000000),1030,73,11.05,39.63,42.93,Clouds

In [18]:
weather_data.to_csv("Resources/city_weather_data.csv", index=False, header=True)